module.exports = {
  verbose: true,
  clearMocks: true,
  collectCoverage: false,
  setupFiles: ['<rootDir>/test-shim.js', '<rootDir>/test-setup.js'],
  collectCoverageFrom: ['src/**/*.tsx'],
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
  coveragePathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/src/pages/',
    '<rootDir>/src/components/',
    '<rootDir>/src/index.tsx',
    '<rootDir>/src/declarations.d.ts',
    '<rootDir>/src/config/api/',
    '<rootDir>/src/App.tsx',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/__tests__/setupTest.js',
    '<rootDir>/src/pages/*.tsx',
    '<rootDir>/src/*.tsx',
    '<rootDir>/src/components/*.tsx',
    '<rootDir>/src/utils/*',
    '<rootDir>/src/index.tsx',
    '<rootDir>/src/declarations.d.ts',
    '<rootDir>/src/config/api/*.js',
  ],
  preset: 'ts-jest',
  testEnvironment: 'node',
};
