declare module '*.png'
declare module '*.jpeg'
declare module 'image/*.jpeg'
declare module 'image/*.svg'
declare module '*.svg'
declare module 'uuid'
/** Dependencies * */
declare module 'react-router-dom'
declare module 'react-router'
declare module 'react-redux'
declare module 'react-dom'
declare module '@heroicons/react/outline'
